/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Kf4IWV9JWXt
 */
import { PlaygroundLabs, Playground} from "@/components/(sections)/landing/PlaygroundLabs";
import { playgroundData } from "./playgroundData";

export default function App() {
  return (
    <div>
      <PlaygroundLabs playgrounds={playgroundData} />
    </div>
  );
}