/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/M1dzg7oP56O
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
**/
import Link from 'next/link';
import { SVGProps } from 'react';
export function Transparent() {
  return (
    <Link href="https://github.com/ebowwar/simulation" passHref>
    <button className="group relative inline-flex items-center justify-center overflow-hidden rounded-lg bg-white px-8 py-3 font-medium text-primary transition-all duration-300 ease-out hover:ring-2 hover:ring-primary focus:outline-none focus:ring-2 focus:ring-primary">
      <span className="absolute inset-0 h-full w-0 bg-primary transition-all duration-300 ease-out group-hover:w-full opacity-10" />
      <span className="relative flex items-center gap-2">
        <GithubIcon className="h-6 w-6 text-primary group-hover:text-white" />
        <span>Built in Public</span>
      </span>
    </button>
    </Link>
  )
}

function GithubIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}
