export const constants_keywords = [
    'Un-Automated',
    'Print on Demand',
    'Amazon Selling',
    'Ecommerce',
    'Human-Centric',
    'Anti-AI',
    'Online Earning',
    'Make Money Online',
    'Sell on Amazon',
    'Design Studio',
    'LLM Integration',
    'Product Research',
    'T-Shirt Design',
    'Mug Design',
    'Phone Case Design',
    'Print on Demand Products',
    'Amazon Print on Demand',
    'Merch by Amazon',
    'Passive Income',
    'Side Hustle',
    'Online Business',
    'Entrepreneurship',
    'AI-Free Ecommerce',
    'Human-Driven Commerce',
    'Creative Freedom',
    'Unemployed Entrepreneurs',
    'Anti-Automation',
    'Pro-Human Innovation',
  ];