/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wY9VrA46q6t
 */
// src/components/sections/landing/landing-footer.tsx
import React from 'react';
import Link from 'next/link';
import { TwitterIcon, InstagramIcon, FacebookIcon, YouTubeIcon } from '@/components/ui/icons/socialmedia';
import landingFooterContent from '@public/raw_data/landing-footer-content.json';

interface FooterLogo {
  href: string;
  repo: string;
  path: string;
  assetType: 'image';
}

interface FooterLink {
  label: string;
  href: string;
}

export function LandingFooter() {
  const {
    companyName,
    companyDescription,
    email,
    address,
    companyLinks,
    plansAndPricingLinks,
    developersLinks,
    assistantsLinks,
    solutionsLinks, // Added solutionsLinks
    helpLinks
  } = landingFooterContent;

  return (
    <footer className="bg-gray-100 dark:bg-gray-900 py-12 sm:py-16">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 sm:gap-12 lg:gap-16 items-start">
          <div className="sm:col-span-2 lg:col-span-1 space-y-8">
            <div className="space-y-2">
              <p className="text-2xl font-semibold">{companyName}</p>
              <p className="text-base leading-relaxed text-gray-500">{companyDescription}</p>
            </div>

            <div className="space-y-4">
              <p className="text-base leading-relaxed text-gray-500">
                Email: <Link href={`mailto:${email}`} className="font-medium">{email}</Link>
              </p>
              <p className="text-base leading-relaxed text-gray-500">
                With ❤️ from: <span className="font-medium">{address}</span>
              </p>
            </div>

            <nav className="flex space-x-4">
              <Link
                className="rounded-lg overflow-hidden border border-gray-200 p-3 flex items-center text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                href="#"
              >
                <FacebookIcon className="h-6 w-6" />
                <span className="sr-only">Facebook</span>
              </Link>
              <Link
                className="rounded-lg overflow-hidden border border-gray-200 p-3 flex items-center text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                href="#"
              >
                <InstagramIcon className="h-6 w-6" />
                <span className="sr-only">Instagram</span>
              </Link>
              <Link
                className="rounded-lg overflow-hidden border border-gray-200 p-3 flex items-center text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                href="#"
              >
                <TwitterIcon className="h-6 w-6" />
                <span className="sr-only">Twitter</span>
              </Link>
              <Link
                className="rounded-lg overflow-hidden border border-gray-200 p-3 flex items-center text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                href="#"
              >
                <YouTubeIcon className="h-6 w-6" />
                <span className="sr-only">Youtube </span>
              </Link>
            </nav>
          </div>

          <div className="space-y-8">
            <div className="font-bold text-gray-700 dark:text-gray-300 mb-4">Get To Know Us!</div>
            <div className="space-y-3">
              {companyLinks.map((link, index) => (
                <Link
                  key={index}
                  className="text-gray-500 hover:underline dark:text-gray-400 transition-colors block"
                  href={link.href}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          <div className="space-y-8">
            <div className="font-bold text-gray-700 dark:text-gray-300 mb-4">Plans & Pricing</div>
            <div className="space-y-3">
              {plansAndPricingLinks.map((link, index) => (
                <Link
                  key={index}
                  className="text-gray-500 hover:underline dark:text-gray-400 transition-colors block"
                  href={link.href}
                >
                  {link.label}
                </Link>
              ))}
            </div>
            <div className="font-bold text-gray-700 dark:text-gray-300 mb-4">Developers</div>
            <div className="space-y-3">
              {developersLinks.map((link, index) => (
                <Link
                  key={index}
                  className="text-gray-500 hover:underline dark:text-gray-400 transition-colors block"
                  href={link.href}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          <div className="space-y-8">
            <div className="font-bold text-gray-700 dark:text-gray-300 mb-4">Assistants</div>
            <div className="space-y-3">
              {assistantsLinks.map((link, index) => (
                <Link
                  key={index}
                  className="text-gray-500 hover:underline dark:text-gray-400 transition-colors block"
                  href={link.href}
                >
                  {link.label}
                </Link>
              ))}
            </div>
            <div className="font-bold text-gray-700 dark:text-gray-300 mb-4">Solutions</div>
            <div className="space-y-3">
              {solutionsLinks.map((link, index) => (
                <Link
                  key={index}
                  className="text-gray-500 hover:underline dark:text-gray-400 transition-colors block"
                  href={link.href}
                >
                  {link.label}
                </Link>
              ))}
            </div>
            <div className="font-bold text-gray-700 dark:text-gray-300 mb-4">Community</div>
            <div className="space-y-3">
              {helpLinks.map((link, index) => (
                <Link
                  key={index}
                  className="text-gray-500 hover:underline dark:text-gray-400 transition-colors block"
                  href={link.href}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 mt-12 sm:mt-16 text-center text-sm text-gray-500">
        &copy; {new Date().getFullYear()} {companyName}. All rights reserved.
      </div>
    </footer>
  );
}