/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NGegO1AcG9i
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TOS() {
  return (
    <div className="w-full max-w-4xl mx-auto py-12 md:py-16 px-4 md:px-6">
      <div className="space-y-8">
        <div className="text-center">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight">Terms of Service & Privacy Policy</h1>
          <p className="mt-2 text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Terms of Service</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>
              By accessing or using our website, you agree to be bound by these terms of service, all applicable laws
              and regulations, and agree that you are responsible for compliance with any applicable local laws.
            </p>
            <p>
              If you do not agree with any of these terms, you are prohibited from using or accessing this site. The
              materials contained in this website are protected by applicable copyright and trademark law.
            </p>
            <p>
              You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create
              derivative works from, transfer, or sell any information, software, products or services obtained from
              this website.
            </p>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Privacy Policy</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>
              We are committed to protecting your privacy. We collect the minimum amount of information about you that
              is commensurate with providing you with a satisfactory service.
            </p>
            <p>
              This policy indicates the information we collect, how we use it, and the steps we take to protect it. By
              using our website, you consent to the collection and use of information in accordance with this policy.
            </p>
            <p>
              We may collect personal information such as your name, email address, and other contact details. We use
              this information to provide you with our services, to improve our products and services, and to send you
              marketing communications if you have opted in to receive them.
            </p>
            <p>
              We take appropriate security measures to protect against unauthorized access, alteration, disclosure or
              destruction of your personal information.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
