graph TD
    AuthenticationSplashView --> AuthenticationViewModel
    AuthenticationSplashView --> ContentView
    AuthenticationSplashView --> TutorialView
    AuthenticationSplashView --> UserManager
    AuthenticationViewModel --> UserManager
    ContentView --> AppSettings
    ContentView --> ExploreView
    ContentView --> NotificationsView
    ContentView --> ProfileView
    ContentView --> TabViewModel
    ContentView --> TimelineView
    InputNameService --> ServerResponse
    MomentCard --> Moment
    NameInputView --> NameInputViewModel
    NameInputView --> ServerResponse
    NameInputView --> VoiceAnalysisCard
    NameInputViewModel --> InputNameService
    NameInputViewModel --> Moment
    NameInputViewModel --> UserManager
    ProfileView --> AppSettings
    ProfileView --> SettingsView
    ProfileView --> UserManager
    ProfileView --> UserProfileViewModel
    SettingsView --> AppSettings
    SettingsView --> SettingsViewModel
    SettingsView --> TutorialView
    SettingsViewModel --> AppSettings
    TimelineView --> MomentCard
    TimelineView --> TimelineViewModel
    TimelineViewModel --> Moment
    TimelineViewModel --> UserManager
    TutorialView --> InputNameService
    TutorialView --> NameInputView
    UserManager --> Moment
    UserProfileViewModel --> UserManager
    VoiceAnalysisCard --> ServerResponse
    caringApp --> AppSettings
    caringApp --> AuthenticationSplashView
    caringApp --> UserManager
